# Generated by Django 4.0.2 on 2024-07-10 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='UserInfo',
        ),
    ]
