# Generated by Django 4.0.2 on 2024-07-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.UUIDField(default='62dc3997-2b8e-474b-891f-ff59b56183c0', editable=False, primary_key=True, serialize=False),
        ),
    ]
